# Generated by Django 2.2.3 on 2020-04-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilddb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
